CREATE TABLE BANK_USER (
    USER_ID NUMBER NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(60) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    MIDDLE_INITIAL VARCHAR2(1),
    GENDER VARCHAR2(1) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    STREET VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(40) NOT NULL,
    STATE VARCHAR2(40) NOT NULL,
    ZIP VARCHAR2(10) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(80) NOT NULL,
    CONSTRAINT BANK_USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT BANK_USER_NAME_UK UNIQUE (USER_NAME)
);
