CREATE TABLE ACCOUNT (
    ACCOUNT_ID NUMBER NOT NULL,
    ACCOUNT_TYPE VARCHAR2(10) NOT NULL,
    ACCOUNT_BALANCE NUMBER NOT NULL,
    ACCOUNT_PIN VARCHAR2(60) NOT NULL,
    DATE_OF_CREATED TIMESTAMP NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_BANK_USER
        FOREIGN KEY (USER_ID) REFERENCES BANK_USER (USER_ID)
);
