CREATE TABLE TRANSACTION_REC (
    TRAN_ID NUMBER NOT NULL,
    ACCOUNT_ID_FROM NUMBER NOT NULL,
    ACCOUNT_ID_TO NUMBER,
    TRANSACTION_TYPE VARCHAR2(10) NOT NULL,
    TRANSACTION_AMOUNT NUMBER NOT NULL,
    TRANSACTION_TIME TIMESTAMP NOT NULL,
    CONSTRAINT TRANSACTION_REC_PK PRIMARY KEY (TRAN_ID),
    CONSTRAINT FK_TRANSACTION_ACCOUNT_FROM
        FOREIGN KEY (ACCOUNT_ID_FROM) REFERENCES ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_TRANSACTION_ACCOUNT_TO
        FOREIGN KEY (ACCOUNT_ID_TO) REFERENCES ACCOUNT (ACCOUNT_ID)
);
